//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Relock.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Relock.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot print to pdf file. The printer {0} is not installed. ähnelt.
        /// </summary>
        public static string CannotPrintToPdfFileThePrinter0IsNotInstalled {
            get {
                return ResourceManager.GetString("CannotPrintToPdfFileThePrinter0IsNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error retrieving key ähnelt.
        /// </summary>
        public static string ErrorRetrievingKey {
            get {
                return ResourceManager.GetString("ErrorRetrievingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while updating registry:  ähnelt.
        /// </summary>
        public static string ErrorWhileUpdatingRegistry {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to get recovery key for:\r\n{0} ähnelt.
        /// </summary>
        public static string FailedToGetRecoveryKeyForRN0 {
            get {
                return ResourceManager.GetString("FailedToGetRecoveryKeyForRN0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to Lock drive:\r\n{0} ähnelt.
        /// </summary>
        public static string FailedToLockDriveRN0 {
            get {
                return ResourceManager.GetString("FailedToLockDriveRN0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ERROR:  ähnelt.
        /// </summary>
        public static string OutputError {
            get {
                return ResourceManager.GetString("OutputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF Files (*.pdf)|*.pdf ähnelt.
        /// </summary>
        public static string PDFFilesPdfPdf {
            get {
                return ResourceManager.GetString("PDFFilesPdfPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print ähnelt.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Printer Not Found ähnelt.
        /// </summary>
        public static string PrinterNotFound {
            get {
                return ResourceManager.GetString("PrinterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program successfully registered in the registry. ähnelt.
        /// </summary>
        public static string ProgramSuccessfullyRegisteredInTheRegistry {
            get {
                return ResourceManager.GetString("ProgramSuccessfullyRegisteredInTheRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program successfully unregistered from the registry. ähnelt.
        /// </summary>
        public static string ProgramSuccessfullyUnregisteredFromTheRegistry {
            get {
                return ResourceManager.GetString("ProgramSuccessfullyUnregisteredFromTheRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recovery code for drive {0} ähnelt.
        /// </summary>
        public static string RecoveryCodeForDrive0 {
            get {
                return ResourceManager.GetString("RecoveryCodeForDrive0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recovery Key ähnelt.
        /// </summary>
        public static string RecoveryKey {
            get {
                return ResourceManager.GetString("RecoveryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registry key not found. ähnelt.
        /// </summary>
        public static string RegistryKeyNotFound {
            get {
                return ResourceManager.GetString("RegistryKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        public static System.Drawing.Icon relock {
            get {
                object obj = ResourceManager.GetObject("relock", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Relock this drive ähnelt.
        /// </summary>
        public static string RelockThisDrive {
            get {
                return ResourceManager.GetString("RelockThisDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save to pdf ähnelt.
        /// </summary>
        public static string SaveToPdf {
            get {
                return ResourceManager.GetString("SaveToPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Relock locks an unlocked bitlocker enabled drive via its context menu
        ///and shows the recovery key as a qr code. The code can be saved as pdf file.
        ///As the first parameter the program requires a drive letter for relocking or
        ////register or /unregister to register in the explorer context menu. ähnelt.
        /// </summary>
        public static string TheProgramRequiresADriveLetterOrRegisterOrUnregisterAsTheFirstParameter {
            get {
                return ResourceManager.GetString("TheProgramRequiresADriveLetterOrRegisterOrUnregisterAsTheFirstParameter", resourceCulture);
            }
        }
    }
}
